apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tls-secret
  namespace: default  # 👈 should match where the secret is created
spec:
  interval: 5m
  releaseName: tls-secret
  chart:
    spec:
      chart: charts/tls-secret  # 👈 relative path inside your Git repo
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    tlsSecret:
      name: dremio-tls
      namespace: default