apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tls-secret
  namespace: default  # 👈 This is where the secret will be created
spec:
  interval: 5m
  releaseName: tls-secret
  chart:
    spec:
      chart: charts/tls-secret   # 👈 relative to Git root
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    tlsSecret:
      name: dremio-tls
      namespace: default
