apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-provisioning
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/dev/secret-provisioning
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
