apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tls-secret
  namespace: default
spec:
  interval: 5m
  releaseName: tls-secret
  chart:
    spec:
      chart: charts/tls-secret
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    tlsSecret:
      name: dremio-tls
      namespace: default
      data:
        tls:
          crt: {{ .Values.tlsSecret.data.tls.crt | quote }}
          key: {{ .Values.tlsSecret.data.tls.key | quote }}
