apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsSecret.name }}
  namespace: {{ .Values.tlsSecret.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsSecret.data.tls.crt | quote }}
  tls.key: {{ .Values.tlsSecret.data.tls.key | quote }}
