tlsSecret:
  name: dremio-tls
  namespace: default
  data:
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIC...
        -----END CERTIFICATE-----
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIE...
        -----END PRIVATE KEY-----